### PR TITLE
More DY and W samples

### PR DESCRIPTION
**Pull request by weihuacern**
Add W1, W2, W2_ext1, W3, W3_ext1, W4, W4_ext1, W4_ext2;
Add DY1-10To50, DY2-10To50, DY3-10To50, DY4-10To50
Add DY1-50ToInf, DY2-50ToInf, DY3-50ToInf, DY4-50ToInf

### CODE REVIEW

**Comment by weihuacern** [comment]
Keep as precious as we can in br because there are some small br like, 0.01760445 for DY450ToInf.

Script to generate br:

import numpy as np

if __name__ == "__main__":
  #                W,          W_ext2,       W1,       W2,  W2_ext1,       W3,  W3_ext1,      W4, W4_ext1,  W4_ext2
  name_WJets = ["W", "W_ext2", "W1", "W2", "W2_ext1", "W3", "W3_ext1", "W4", "W4_ext1",  "W4_ext2"]
  nevt_WJets = np.array([29705748, 57026058, 45367044, 29878415, 30319351, 19798117, 39269431, 9170576, 2073275, 18751462])
  print(name_WJets)
  print(nevt_WJets / np.sum(nevt_WJets))

  #DY, 10To50
  name_DY10To50  = ["DY-10-50", "DY-10-50_ext1", "DY1-10-50", "DY2-10-50", "DY3-10-50", "DY4-10-50"]
  nevt_DY10To50  = np.array([30920596, 40381391, 39840774, 19442927, 4964197, 2087849])
  print(name_DY10To50)
  print(nevt_DY10To50 / np.sum(nevt_DY10To50))

  #DY, 50ToInf
  name_DY50ToInf = ["DY-50-Inf_ext1", "DY-50-Inf_ext2", "DY1-50-Inf", "DY2-50-Inf", "DY3-50-Inf", "DY4-50-Inf"]
  nevt_DY50ToInf = np.array([49144274, 96658943, 62627174, 19970551, 5856110, 4197868])
  print(name_DY50ToInf)
  print(nevt_DY50ToInf / np.sum(nevt_DY50ToInf))

Result:
gihuadeMacBook-Air:Haa4b ustc-weihua$ python brGen.py 
['W', 'W_ext2', 'W1', 'W2', 'W2_ext1', 'W3', 'W3_ext1', 'W4', 'W4_ext1', 'W4_ext2']
[ 0.10557934  0.20268042  0.16124228  0.10619303  0.10776019  0.07036591
  0.13957032  0.03259381  0.00736878  0.06664592]
['DY-10-50', 'DY-10-50_ext1', 'DY1-10-50', 'DY2-10-50', 'DY3-10-50', 'DY4-10-50']
[ 0.22465203  0.29338896  0.28946113  0.1412616   0.03606712  0.01516916]
['DY-50-Inf_ext1', 'DY-50-Inf_ext2', 'DY1-50-Inf', 'DY2-50-Inf', 'DY3-50-Inf', 'DY4-50-Inf']
[ 0.20609461  0.40535521  0.26263737  0.0837498   0.02455856  0.01760445]

**Comment by georgia14** [comment]
Hi @weihuacern,

I think you need to update the cross-sections of all these samples: W+Njets and DY+Njets. Each process W+Njet, with N=1,2,3,4 has different xsec than the inclusive sample.
In addition, WJet is inclusive so will overlap with W1Jet or W2Jet etc etc . The same for DYJet and DY1Jet, DY2Jet, etc , so we need to add them properly if we use all of them. 

Cheers,
Georgia

**Comment by weihuacern** [comment]
Hi @georgia14 ,
I found xSec in the MCM: 

Table of new XJet samples, xSec from MCM: 
MC Sample | Prep_id | xSec(pb^-1, mcm) | Nevts
-- | -- | -- | --
/W1JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM | HIG-RunIISummer16MiniAODv2-00388 | 9493 | 45367044
/W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM | HIG-RunIISummer16MiniAODv2-00389 | 3120 | 29878415
/W2JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6_ext1-v1/MINIAODSIM | HIG-RunIISummer16MiniAODv2-01359 | 3120 | 30319351
/W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM | HIG-RunIISummer16MiniAODv2-00390 | 942.3 | 19798117
/W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6_ext1-v1/MINIAODSIM | HIG-RunIISummer16MiniAODv2-01367 | 942.3 | 39269431
/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM | HIG-RunIISummer16MiniAODv2-00391 | 524.2 | 9170576
/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6_ext1-v1/MINIAODSIM | HIG-RunIISummer16MiniAODv2-00387 | 524.2 | 2073275
/W4JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6_ext2-v1/MINIAODSIM | HIG-RunIISummer16MiniAODv2-01085 | 524.2 | 18751462
  |   |   |  
/DY1JetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM | HIG-RunIISummer16MiniAODv2-00807 | 725 | 39840774
/DY2JetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM | HIG-RunIISummer16MiniAODv2-00808 | 394.5 | 19442927
/DY3JetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM | HIG-RunIISummer16MiniAODv2-00809 | 96.47 | 4964197
/DY4JetsToLL_M-10to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM | HIG-RunIISummer16MiniAODv2-00810 | 34.84 | 2087849
  |   |   |  
/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM | HIG-RunIISummer16MiniAODv2-00924 | 1016 | 62627174
/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM | HIG-RunIISummer16MiniAODv2-00925 | 331.4 | 19970551
/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM | HIG-RunIISummer16MiniAODv2-00923 | 96.36 | 5856110
/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM | HIG-RunIISummer16MiniAODv2-00926 | 51.4 | 4197868

But I found the same physics process, DYJetsToLL_M-50, SUSY recommendation page have 5765.4, but MCM have 4895. 

Can we use the generator(LHE, or GS) xSec from MCM?

**Comment by weihuacern** [comment]
Hi @georgia14 ,
I update the sample.json with current mcm xSec and fixed br.
Script to generate br:

```python
import numpy as np

def printBr(name, nevt):
  print(name)
  print(nevt / np.sum(nevt))

if __name__ == "__main__":
  #WJets
  name_WJets = ["W", "W_ext2"]#, "W1", "W2", "W2_ext1", "W3", "W3_ext1", "W4", "W4_ext1",  "W4_ext2"]
  nevt_WJets = np.array([29705748, 57026058])#, 45367044, 29878415, 30319351, 19798117, 39269431, 9170576, 2073275, 18751462])
  printBr(name_WJets, nevt_WJets)

  #W1Jets
  name_W1Jets = ["W1"]
  nevt_W1Jets = np.array([45367044])
  printBr(name_W1Jets, nevt_W1Jets)

  #W2Jets
  name_W2Jets = ["W2", "W2_ext1"]
  nevt_W2Jets = np.array([29878415, 30319351])
  printBr(name_W2Jets, nevt_W2Jets)                                                                                                                                                                         

  #W3Jets
  name_W3Jets = ["W3", "W3_ext1"]
  nevt_W3Jets = np.array([19798117, 39269431])
  printBr(name_W3Jets, nevt_W3Jets)                                                                                                                                                                         

  #W4Jets
  name_W4Jets = ["W4", "W4_ext1",  "W4_ext2"]
  nevt_W4Jets = np.array([9170576, 2073275, 18751462])
  printBr(name_W4Jets, nevt_W4Jets)                                                                                                                                                                         

  #DY, 10To50
  name_DY10To50  = ["DY-10-50", "DY-10-50_ext1"]#, "DY1-10-50", "DY2-10-50", "DY3-10-50", "DY4-10-50"]
  nevt_DY10To50  = np.array([30920596, 40381391])#, 39840774, 19442927, 4964197, 2087849])
  printBr(name_DY10To50, nevt_DY10To50)

  #DY, 50ToInf
  name_DY50ToInf = ["DY-50-Inf_ext1", "DY-50-Inf_ext2"]#, "DY1-50-Inf", "DY2-50-Inf", "DY3-50-Inf", "DY4-50-Inf"]
  nevt_DY50ToInf = np.array([49144274, 96658943])#, 62627174, 19970551, 5856110, 4197868])
  printBr(name_DY50ToInf, nevt_DY50ToInf)
```

**Comment by georgia14** [comment]
Hi @weihuacern 

Thanks a lot for the update. Still, I think we need to fix the overlap between the inclusive WJets and W**x**Jets or DYJets and DY**x**Jets samples, because we cannot just add these samples as is in the json file right now.

Btw, could you please drop the submit.sh commit so that I can merge?

Thanks, Georgia

**Comment by weihuacern** [comment]
Hi @georgia14 , 
I resolve the conflict on submit.sh. 
For the overlap, a first think of me is to do the gen jet veto on the inclusive sample, if we want to use WXJets or DYXJets samples.

**Comment by georgia14** [comment]
Yes, the only problem is that we do not store the gen jet information in the ntuples currently due increased size . Could you check if this can be done in the analysis using parton level information instead?
Thanks a lot, Georgia

**Pull request merged**
