### PR TITLE
Adding W->lv HT-binned samples

### PR DESCRIPTION
**Pull request by aminghiasi**
As described in the title

### CODE REVIEW

**Comment by georgia14** [comment]
hi @aminghiasi 

we need the **RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV** 
not the Spring16 versions. (I had explicitly said that in my email)

thanks, Georgia

**Comment by aminghiasi** [comment]
hi @georgia14,

I couldn't find "RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV" versions. 

Best,
Amin

**Comment by georgia14** [comment]
I can find them in DAS, for example:
/WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6_ext2-v1/MINIAODSIM

**Comment by aminghiasi** [comment]
Hi @georgia14,

Right. Thanks! I changed the versions to "RunIISummer16MiniAODv2-PUMoriond17"

Best,
Amin

**Comment by aminghiasi** [comment]
I did everything from the scratch. Copy-pasted the dataset names from DAS and calculated BRs again.

**Pull request closed without merging**
