### PR TITLE
Replacing QCD MuEnr sample with QCD MuEnrichedPt5 samples

### PR DESCRIPTION
**Pull request by aminghiasi**
Add described in the title

### CODE REVIEW

**Comment by aminghiasi** [comment]
I tried to submit jobs to crab but my jobs failed with this error: 

	CmsRunFailure
		CMSSW error message follows.
		Fatal Exception
		An exception of category 'UnknownUserFloat' occurred while
		   [0] Processing run: 1 lumi: 23343 event: 50944398
		   [1] Running path 'p'
		   [2] Calling event method for module mainNtuplizer/'mainNtuplizer'
		Exception Message:
		Requested UserFloat pileupJetId:fullDiscriminant is not available! Possible UserFloats are:
		pileupJetId:fullDiscriminant caloJetMap:pt caloJetMap:emEnergyFraction vtxMass vtxNtracks vtx3DVal vtx3DSig vtxPx vtxPy vtxPz vtxPosX vtxPosY vtxPosZ

**Comment by georgia14** [comment]
Hi, of course, because you added the Spring 2015 samples in 7_4_x? 
We need the Summer 2016 PUMoriond samples : RunIISummer16MiniAODv2-PUMoriond17

**Comment by aminghiasi** [comment]
I updated the PR. Now, this PR changes four things in samples2016.json and samples2016.json.tmp:
1- I put xsec*br in xsec and 1.0 for br (if there is no extension to the dataset)
2- I added MuEnriched samples
3- There were some EMEnriched extension datasets missing. I added those to the JSON file. (Was there any reason that we didn't add all datasets and extensions from the beginning?)
4- Before, I had separated bcToE QCD samples from other QCD datasets to be able to monitor the behavior of bcToE directly. I don't think that we need to keep bcToE samples separate anymore. Now, everything is combined.

**Comment by aminghiasi** [comment]
Also, I submitted the code to crab to run on all QCD samples. Hopefully, we will have the ntuples in a day or two.

**Comment by georgia14** [comment]
hi @aminghiasi 

Ok looks good, thanks a lot.
There is one update that needs to be done : it is better to avoid BRs like 0.33333333 . In addition, the BR for a dataset with an extension needs to be weighted by the number of events in the dataset. For example, if Dataset1 has 1000 events and Dataset2 (ext1) has 4000 events, then BR1=0.2 and BR2=0.8. 
Thanks, Georgia

**Comment by aminghiasi** [comment]
Hi @georgia14,
Thanks for the comments. I made the changes to the cross-section and made the plots again. The plots look reasonable.

**Pull request merged**
